config/routes.rb
  Rails.application.routes.draw do

  resources :images

  root :to => "pages#home"
  root to: 'images#index'
  resources :products, :products
  resources :users

  get '/login' => 'session#new' # login form
  post '/login' => 'session#create' # perform a login
  delete '/login' => 'session#destroy' # perform a log out

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
end

app/models/listing.rb
class Listing < ApplicationRecord
  has_many :products
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :bigint(8)        not null, primary key
#  title       :text
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Product < ApplicationRecord
  belongs_to :listing, :optional => true
  belongs_to :user, :optional => true
end

app/models/user.rb
class User < ApplicationRecord
   has_secure_password
   has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :fetch_user

  private
  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present? # This prevents horrors when reseeding
  end

  def check_for_login
    redirect_to login_path unless @current_user.present?
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:title, :link, :description)
    end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  def new
    @listing = Listing.new
  end

  def create
    listing = @current_user.listings.create listing_params
    redirect_to root_path
  end

  private
  def listings_params
    params.require(:listing).permit(:price, :location, :category)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController


  def index
    # @products = Product.all.order("created_at DESC")
    if @current_user.present?
    @products = @current_user.products.order("created_at DESC")
  else
    @products = Product.all.order("created_at DESC")
  end
end
  def show
    @product = Product.find params[:id]
  end

  def edit
    @product = Product.find params[:id]
  end

  def update
    product = Product.find params[:id]
    product.update product_params
    cloudinary = Cloudinary::Uploader.upload( params[ "product" ][ "image" ] )
    product.image = cloudinary["url"]
    product.save
    redirect_to product
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new product_params
    cloudinary = Cloudinary::Uploader.upload( params[ "product" ][ "image" ] )
    @product.image = cloudinary["url"]
    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def destroy
    product = Product.find params[:id]
    product.destroy
    redirect_to products_path
   end

  private

   def product_params
     params.require(:product).permit(:title, :description, :price)
   end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Invalid username or password"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_login, :only => [:index]

    def index
      @users = User.all
    end



    def new
      @user = User.new
    end

    def create
      @user = User.create user_params
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_path #Redirect to home if the account is valid
       else
        render :new #Let them retry the form again
      end
    end

    private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/images/_form.html.erb
<%= form_with(model: image, local: true) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_area :link %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Images</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Link</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.title %></td>
        <td><%= image.link %></td>
        <td><%= image.description %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @image.title %>
</p>

<p>
  <strong>Link:</strong>
  <%= @image.link %>
</p>

<p>
  <strong>Description:</strong>
  <%= @image.description %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sell Me</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <nav class="navbar navbar-inverse navbar-fixed-top ">
    <div class="container-fluid">
      <div class="navbar-header navbar-fixed-top">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

      </div>
      <div class="collapse navbar-collapse navbar-fixed-top" id="myNavbar">
        <ul class="nav navbar-nav ">
          <li class="active">
            <%= link_to 'Home', root_path %>
          </li>
          <li>
            <%= link_to 'Products', products_path %>
          </li>
          <li>
            <%= link_to 'Sell', new_product_path %>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right  ">
          <ul>
              <% if @current_user.present? %>
              <%= link_to "Sign out #{ @current_user.email} ", login_path, :method => 'delete' %>
                <% else  %>
                <li>
                   <%= link_to 'Sign up', new_user_path %>
                </li>
                <li>
                  <%= link_to 'Log in ', login_path %>
                </li>
          </ul>
          </div>
              <% end %>

          </a>
        </ul>
      </div>
    </div>
  </nav>

  <body>

    <%= yield %>




  </body>
</html>

app/views/listings/_form.html.erb
<%= form_for @listing do |f| %>

  <%= f.label :category %>
  <%= f.text_field :category %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.submit %>
  <% end %>

app/views/listings/edit.html.erb
<h1>Edit listing</h1>

<%= render :partial => 'form' %>

app/views/listings/index.html.erb
<h1>All Listing</h1>

app/views/listings/new.html.erb
<h1>New listing</h1>

app/views/listings/show.html.erb
<h1>Show listing</h1>

app/views/pages/home.html.erb
<div class="jumbotron">

<div class="container">
  <h1>Sell me</h1>
  <p>The best free local classifieds site to buy and sell your: cars, furniture, clothes, books, games, computers, and electronics!</p>
  <p><a class="btn btn-primary btn-lg" href="#" role="button">Get Started</a></p>
</div>

</div>

 <% if @current_user.present? %>
   <h1>Welcome back  <%=  @current_user.email %></h1>

<% end %>

<div class="row">
    <% Product.all.each_with_index do |p, i| %>
    <div class="col-sm-4">
      <div class="productitem<%= i+1 %>">
        <%= image_tag p.image, :class => "productitem#{ i+1 }__img" if p.image.present? %>
        <h2 class="productitem<%= i+1 %>__title"></h2>
        <%= link_to p.title, product_path(p), :class => "productitem#{i+1}__price" %>
        <span class="productitem<%=i+1%>__price"><%=  p.price %></span>
      </div>
    </div>
    <% end %>
</div>


<footer class="container-fluid text-center">
  <p>Sell me Copyright</p>
  <form class="form-inline">Get newsletter:
    <input type="email" class="form-control" size="50" placeholder="Email Address">
    <button type="button" class="btn btn-danger">Sign Up</button>
  </form>
</footer>

app/views/products/_form.html.erb
<%= form_for(@product, :html => { :multipart => true }) do |f| %>

<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :description %>
<%= f.text_field :description %>

<%= f.label :price %>
<%= f.text_field :price %>

<%= f.label :image %>
<%= f.file_field :image %>

<%= f.button :update %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit product</h1>


<%= render :partial => 'form' %>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
      <% @products.each_with_index do |p, i| %>
      <div class="col-sm-4">
        <div class="productitem1<%= i+1 %>">
          <%= image_tag p.image, :class => "productitem#{ i+1 }__img" if p.image.present? %>
          <h2 class="productitem1<%= i+1 %>__title"></h2>
          <%= link_to p.title, product_path(p), :class => "productitem#{i+1}__price" %>
          <span class="productitem1<%=i+1%>__price"><%=  p.price %></span>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render :partial => 'form' %>

app/views/products/show.html.erb
<div class="row">
<div class="col-sm-4">
  <div class="productitem1">
    <%= image_tag @product.image, :class => "productitem1__img" if @product.image.present? %>
    <h2 class="productitem1__title"></h2>
    <%= link_to @product.title, product_path(@product), :class => "productitem1__price" %>
    <span class="productitem1__price"><%=  @product.price %></span>
  </div>
</div>
</div>



<div class="controls">
  <%= link_to 'Edit', edit_product_path(@product) %>
  <%= link_to 'Delete', product_path(@product), :method => 'delete' ,:data => {:confirm => 'Are you sure you want to delete this product ?'}%>

</div

app/views/session/new.html.erb
<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->
    <h2 class="active"> Log In </h2>


    <!-- Icon -->
    <div class="fadeIn first">
      <img src="http://danielzawadzki.com/codepen/01/icon.svg" id="icon" alt="User Icon" />
    </div>

    <!-- Login Form -->
    <form>
      <input type="text" id="login" class="fadeIn second" name="login" placeholder="login">
      <input type="text" id="password" class="fadeIn third" name="login" placeholder="password">
      <input type="submit" class="fadeIn fourth" value="Log In">
    </form>

    <!-- Remind Passowrd -->
    <div id="formFooter">
      <a class="underlineHover" href="#">Forgot Password?</a>
    </div>

  </div>
</div>

app/views/users/index.html.erb
<h1>All Users: <%=  User.count %></h1>
<%  @users.each do |user| %>
  <p><%=  user.email  %></p>
  <% end %>

app/views/users/new.html.erb
<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->
    <h2 class="active"> Sign up </h2>


    <!-- Icon -->
    <div class="fadeIn first">
      <img src="http://danielzawadzki.com/codepen/01/icon.svg" id="icon" alt="User Icon" />
    </div>

    <!-- Login Form -->
    <form>
      <input type="text" id="login" class="fadeIn second" name="email" placeholder="email">

      <input type="text" id="password" class="fadeIn third" name="login" placeholder="password">

      <input type="text" id="password" class="fadeIn third" name="login" placeholder="password confirmation">
          <input type="submit" class="fadeIn fourth" value="Sign up">
    </form>

    <!-- Remind Passowrd -->
    <div id="formFooter">
      <a class="underlineHover" href="#">Forgot Password?</a>
    </div>

  </div>
</div>